### ISSUE TITLE
Publish this Arduino library

### ISSUE THREAD

**Issue by lboue** [m5stack/M5Unit-BLDC#1]
Hello,

Could you publish this Arduino library to make it accessible in the library manager?

Regards

**Comment by TinyuZhao** [comment]
I'll release the version

**Comment by lboue** [comment]
> I'll release the version

Thanks @Tinyu-Zhao

**Comment by TinyuZhao** [comment]
> > I'll release the version
> 
> Thanks @Tinyu-Zhao

Just wait patiently and you can find it in the library index.
https://github.com/arduino/library-registry/pull/4821
